### Importing Libraries and the Dataset

In [150]:
import pandas as pd
import numpy as np
import warnings

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from pprint import pprint
%matplotlib inline
from matplotlib.lines import Line2D

# Modelling
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

warnings.filterwarnings("ignore")

In [151]:
filepath = 'Data/CountriesOnly.csv'

df = pd.read_csv(filepath, encoding = 'unicode_escape')
df = df.drop(['Unnamed: 0', 'Unnamed: 14'], axis = 1)

# Removing rows where country=World
worldDf = df[(df['country'] == 'World')].index
df.drop(worldDf , inplace=True)
df.head()

,country,UNRegion,year,record,cropLand,grazingLand,forestLand,fishingGround,builtupLand,carbon,total,GDP,population,countryCode
0,Armenia,Asia,1992,BiocapPerCap,1.611286e-01,0.135023,0.083836,0.013718,0.033669,0.000000e+00,4.273741e-01,949.033,3449000.0,1.0
1,Armenia,Asia,1992,BiocapTotGHA,5.558130e+05,465763.337400,289190.662300,47320.224590,116139.598200,0.000000e+00,1.474227e+06,949.033,3449000.0,1.0
2,Armenia,Asia,1992,EFConsPerCap,3.909225e-01,0.189137,0.000001,0.004138,0.033669,1.112225e+00,1.730092e+00,949.033,3449000.0,1.0
3,Armenia,Asia,1992,EFConsTotGHA,1.348487e+06,652429.066600,4.327841,14272.803690,116139.598200,3.836620e+06,5.967954e+06,949.033,3449000.0,1.0
4,Armenia,Asia,1992,EFExportsPerCap,1.124910e-03,0.002283,0.000000,0.000438,0.000000,4.819043e-02,5.203676e-02,949.033,3449000.0,1.0

In [152]:
print("Number of countries: ", len(df.country.unique()))

Number of countries:  203

In [153]:
df[(df['country'] == 'South Africa') & (df['year'] == 2011)]

,country,UNRegion,year,record,cropLand,grazingLand,forestLand,fishingGround,builtupLand,carbon,total,GDP,population,countryCode
69200,South Africa,Africa,2011,BiocapPerCap,NaN,NaN,NaN,NaN,NaN,NaN,1.070094e+00,7493.3,52237000.0,202.0
69201,South Africa,Africa,2011,BiocapTotGHA,NaN,NaN,NaN,NaN,NaN,NaN,5.589881e+07,7493.3,52237000.0,202.0
69202,South Africa,Africa,2011,EFConsPerCap,NaN,NaN,NaN,NaN,NaN,NaN,3.399956e+00,7493.3,52237000.0,202.0
69203,South Africa,Africa,2011,EFConsTotGHA,NaN,NaN,NaN,NaN,NaN,NaN,1.776045e+08,7493.3,52237000.0,202.0
69204,South Africa,Africa,2011,EFExportsPerCap,NaN,NaN,NaN,NaN,NaN,NaN,9.496150e-01,7493.3,52237000.0,202.0
69205,South Africa,Africa,2011,EFExportsTotGHA,NaN,NaN,NaN,NaN,NaN,NaN,4.960532e+07,7493.3,52237000.0,202.0
69206,South Africa,Africa,2011,EFImportsPerCap,NaN,NaN,NaN,NaN,NaN,NaN,6.722535e-01,7493.3,52237000.0,202.0
69207,South Africa,Africa,2011,EFImportsTotGHA,NaN,NaN,NaN,NaN,NaN,NaN,3.511671e+07,7493.3,52237000.0,202.0
69208,South Africa,Africa,2011,EFProdPerCap,NaN,NaN,NaN,NaN,NaN,NaN,3.677318e+00,7493.3,52237000.0,202.0
69209,South Africa,Africa,2011,EFProdTotGHA,NaN,NaN,NaN,NaN,NaN,NaN,1.920931e+08,7493.3,52237000.0,202.0

### Removing null values

In [154]:
df.isna().sum()

country              0
UNRegion           290
year                 0
record               0
cropLand         25040
grazingLand      25040
forestLand       25040
fishingGround    25040
builtupLand      25040
carbon           25040
total                0
GDP              21140
population           0
countryCode       5150
dtype: int64

In [157]:
# Remove rows where all mentioned columns are null
df = df.dropna(subset=['cropLand', 'grazingLand', 'forestLand', 'fishingGround', 'builtupLand', 'carbon'], how='all')
df.isna().sum()

country              0
UNRegion           170
year                 0
record               0
cropLand             0
grazingLand          0
forestLand           0
fishingGround        0
builtupLand          0
carbon               0
total                0
GDP              13080
population           0
countryCode       1650
dtype: int64

### Statistical Analysis

In [6]:
print("Statistical summary of each colums in the dataset:")
df.describe().T.style.background_gradient(axis=None)

Statistical summary of each colums in the dataset:

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68810 entries, 0 to 94419
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        68810 non-null  object
 1   UNRegion       68640 non-null  object
 2   year           68810 non-null  int64
 3   record         68810 non-null  object
 4   cropLand       68810 non-null  float64
 5   grazingLand    68810 non-null  float64
 6   forestLand     68810 non-null  float64
 7   fishingGround  68810 non-null  float64
 8   builtupLand    68810 non-null  float64
 9   carbon         68810 non-null  float64
 10  total          68810 non-null  float64
 11  GDP            55730 non-null  float64
 12  population     68810 non-null  float64
 13  countryCode    67160 non-null  float64
dtypes: float64(10), int64(1), object(3)
memory usage: 7.9+ MB

In [8]:
shape = df.shape
print("Shape of Dataset is", shape, "\n")
print("---------------------------------")
print("Types of Data Attributes:")
print(df.dtypes, "\n")

Shape of Dataset is (68810, 14)

---------------------------------
Types of Data Attributes:
country           object
UNRegion          object
year               int64
record            object
cropLand         float64
grazingLand      float64
forestLand       float64
fishingGround    float64
builtupLand      float64
carbon           float64
total            float64
GDP              float64
population       float64
countryCode      float64
dtype: object

In [9]:
# Checking for duplicate values
df.duplicated().unique()

array([False])

### Ecological Debtor and Creditor - df_classify

- <code>bioTotal</code> is the BioCapTotGHA record
- <code>ecoTotal</code> is the sum of all records for EcoTotGHA under each record type

ex: For Armenia in 1961 under cropLand, <code>ecoTotal = cropLand(EFConsTotGHA) + cropLand(EFExportsTotGHA) + cropLand(EFImportsTotGHA) + cropLand(EFProdTotGHA) </code>

In [10]:
# Defining the EQF for each resource type
crop_eqf = 2.51
graze_eqf = 0.46
forest_eqf = 1.26
fishing_eqf = 0.37
carbon_eqf = 1.26
builtup_eqf = 2.51

biocapacity_records = ['BiocapTotGHA']
ecological_records = ['EFConsTotGHA','EFExportsTotGHA', 'EFImportsTotGHA', 'EFProdTotGHA']

biototal = 0
ecototal = 0
df_footprint = pd.DataFrame(columns=['country','year','record','bioTotal','ecoTotal'])

id_group=df.groupby(['country','year'])
id_group

landType = ['cropLand', 'grazingLand', 'forestLand', 'fishingGround', 'builtupLand', 'carbon']

for l in landType:
    for g_idx, group in id_group:
        biototal = 0
        ecototal = 0
        for r_idx, row in group.iterrows():
            if row['record'] in biocapacity_records:
                biototal = biototal + row[l]
            elif row['record'] in ecological_records:
                ecototal = ecototal + row[l]

        df2 = {'country': row['country'], 'countryCode': row['countryCode'] , 'year': row['year'], 'record': l, 'bioTotal': biototal, 'ecoTotal': ecototal}
        df_footprint = df_footprint.append(df2, ignore_index = True)

df_footprint = df_footprint.groupby(['country'], as_index=False).apply(pd.DataFrame.sort_values, 'year').reset_index()
df_footprint = df_footprint.drop(['level_0', 'level_1'], axis = 1)
df_footprint

,country,year,record,bioTotal,ecoTotal,countryCode
0,Afghanistan,1961,cropLand,4.990785e+06,1.010593e+07,2.0
1,Afghanistan,1961,fishingGround,0.000000e+00,9.706928e+02,2.0
2,Afghanistan,1961,grazingLand,6.212850e+06,1.064433e+07,2.0
3,Afghanistan,1961,builtupLand,2.722616e+05,5.445231e+05,2.0
4,Afghanistan,1961,carbon,0.000000e+00,5.596314e+05,2.0
...,...,...,...,...,...,...
41281,Zimbabwe,2018,fishingGround,1.425158e+05,2.284124e+05,181.0
41282,Zimbabwe,2018,grazingLand,4.357868e+06,8.762956e+06,181.0
41283,Zimbabwe,2018,cropLand,2.203482e+06,6.553660e+06,181.0
41284,Zimbabwe,2018,builtupLand,3.350453e+05,6.700907e+05,181.0
41285,Zimbabwe,2018,carbon,0.000000e+00,1.239203e+07,181.0

- <code>bioFootprint</code> is the bioTotal multiplied with the equivalence value from the above cell
- <code>ecoFootprint</code> is calculated similarly

In [11]:
for index, row in df_footprint.iterrows():
    if df_footprint.at[index, 'record'] == 'cropLand':
        df_footprint.at[index, 'bioFootprint'] = df_footprint.at[index, 'bioTotal'] * crop_eqf
        df_footprint.at[index, 'ecoFootprint'] = df_footprint.at[index, 'ecoTotal'] * crop_eqf
    elif df_footprint.at[index, 'record'] == 'fishingGround':
        df_footprint.at[index, 'bioFootprint'] = df_footprint.at[index, 'bioTotal'] * fishing_eqf
        df_footprint.at[index, 'ecoFootprint'] = df_footprint.at[index, 'ecoTotal'] * fishing_eqf
    elif df_footprint.at[index, 'record'] == 'forestLand':
        df_footprint.at[index, 'bioFootprint'] = df_footprint.at[index, 'bioTotal'] * forest_eqf
        df_footprint.at[index, 'ecoFootprint'] = df_footprint.at[index, 'ecoTotal'] * forest_eqf
    elif df_footprint.at[index, 'record'] == 'grazingLand':
        df_footprint.at[index, 'bioFootprint'] = df_footprint.at[index, 'bioTotal'] * graze_eqf
        df_footprint.at[index, 'ecoFootprint'] = df_footprint.at[index, 'ecoTotal'] * graze_eqf
    if df_footprint.at[index, 'record'] == 'builtupLand':
        df_footprint.at[index, 'bioFootprint'] = df_footprint.at[index, 'bioTotal'] * builtup_eqf
        df_footprint.at[index, 'ecoFootprint'] = df_footprint.at[index, 'ecoTotal'] * builtup_eqf
    elif df_footprint.at[index, 'record'] == 'carbon':
        df_footprint.at[index, 'bioFootprint'] = df_footprint.at[index, 'bioTotal'] * carbon_eqf
        df_footprint.at[index, 'ecoFootprint'] = df_footprint.at[index, 'ecoTotal'] * carbon_eqf

In [12]:
df_footprint
df_footprint.to_csv('Data/NEW/Footprint.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Data/NEW/Footprint.csv'

- Summing up the <code>bioTotal</code> and <code>ecoTotal</code> across all land types grouped by country and year
- A country is then classified as an <b>ecological creditor</b> if their <code>bioFootprint > ecoFootprint</code> and an <b>ecological debtor</b> if their <code>bioFootprint < ecoFootprint</code>

In [ ]:
df_classify = pd.DataFrame(columns=['country','year','footprintType'])

ecoF = 0
bioF = 0

id_group=df_footprint.groupby(['country','year'])
id_group

for g_idx, group in id_group:
    for r_idx, row in group.iterrows():
        bioF = bioF + row['bioFootprint']
        ecoF = ecoF + row['ecoFootprint']
        
    if bioF > ecoF:
        df2 = {'country': row['country'], 'year': row['year'], 'bioTot': bioF, 'ecoTot': ecoF, 'footprintType': 'Creditor'}
    else:
        df2 = {'country': row['country'], 'year': row['year'], 'bioTot': bioF, 'ecoTot': ecoF, 'footprintType': 'Debter'}
    
    df_classify = df_classify.append(df2, ignore_index = True)

In [ ]:
df_classify

In [ ]:
df_classify.to_csv('Data/Modelling/Classification.csv')
df_footprint.to_csv('Data/Modelling/PredictionDataset.csv')
df_classify

### Making the dataset ready for modelling

In [ ]:
def navalues(data):
    cols = data.columns
    for j in cols:
        for i in range(0,len(data)):
             if data[j][i].isna():
                data[j][i] = data[j][i-1]
                
def scale(df):
    sc = StandardScaler()
    df[['bioTotal', 'ecoTotal', 'bioFootprint', 'ecoFootprint']] = sc.fit_transform(df[['bioTotal', 'ecoTotal', 'bioFootprint', 'ecoFootprint']])
    return df

def reverse_scale(df):
    sc = StandardScaler()
    return sc.inverse_transform(df)

def encode(df):
    if 'country' in df.columns.unique():
        df = df.drop(['country'], axis=1)
    if 'record' in df.columns.unique():
        df = pd.get_dummies(df, columns=["record"])
    return df

def prepare_timeseries(df, record):
    return df.set_index(['year'])

def prepareCountryDf(df, countryCode):
    df = df.loc[df['countryCode'] == countryCode]
    return df

In [ ]:
df_footprint

In [ ]:
df_others = encode(scale(df_footprint))
df_others.index = df_others.year
df_others = df_others.drop(['year'], 1)
print("Shape of the dataset: ", df_others.shape)
print("-----------------------------------")
df_others.head()

In [ ]:
df_footprint.to_csv('Data/NEW/Footprint.csv')

### Correlation Analysis

In [ ]:
plt.figure(figsize=(8,6))
ax = sns.heatmap(df_footprint.select_dtypes(include='number').corr(), annot = True, linewidth=0.5, fmt='0.1f', cmap = 'RdBu_r')
ax.set_ylim(sorted(ax.get_xlim(), reverse=True))
plt.show()

In [ ]:
df_footprint.corr()

## Modeling

In [ ]:
import math
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import seed
seed(1)
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import tensorflow
tensorflow.random.set_seed(1)
from tensorflow.python.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [ ]:
model = Sequential()
model.add(Dense(8, input_dim=10, kernel_initializer='normal', activation='relu'))
model.add(Dense(2670, activation='relu'))
model.add(Dense(1, activation='linear'))
model.summary()

In [ ]:
X = df_others.drop(["ecoFootprint"], 1)
y = df_others["ecoFootprint"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=21)

X_train = np.asarray(X_train).astype('float32')
X_val = np.asarray(X_val).astype('float32')
y_train = np.asarray(y_train).astype('float32')
y_val = np.asarray(y_val).astype('float32')

In [ ]:
model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])
history=model.fit(X_train, y_train, epochs=10, batch_size=150, verbose=1, validation_split=0.2)
predictions = model.predict(X_val)

In [ ]:
predictions

In [ ]:
mean_absolute_error(y_val, predictions)

In [ ]:
math.sqrt(mean_squared_error(y_val, predictions))

In [ ]:
np.mean(y_val)

In [ ]:
np.mean(predictions)

### LSTM

In [ ]:
df_modeling_ts = df_modeling
df_modeling_ts.index = df_modeling_ts.year
df_modeling_ts = df_modeling.drop(['year'], axis=1)
df_modeling_ts

In [ ]:
from matplotlib import pyplot

values = df_modeling_ts.values
# specify columns to plot
groups = [0, 1, 2, 3, 5, 6, 7]
i = 1
# plot each column
pyplot.figure()
for group in groups:
    pyplot.subplot(len(groups), 1, i)
    pyplot.plot(values[:, group])
    pyplot.title(df_modeling_ts.columns[group], y=0.5, loc='right')
    i += 1
pyplot.show()